config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :involved_companies
  # resources :users
  resources :genres
  resources :platforms

  
  resources :games do 
    post "add_genre", on: :member
    post "add_platform", on: :member
    post "add_developer", on: :member
    post "add_publisher", on: :member
    delete "remove_genre", on: :member
    delete "remove_platform", on: :member
    delete "remove_developer", on: :member
    delete "remove_publisher", on: :member

    resources :critics, only: %i[create destroy]
  end

  resources :companies do
    resources :critics, only: %i[create destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "games#index"
  # get "/profile", to: "users#show", as: "user"
end

app/models/game.rb
class Game < ApplicationRecord
    has_one_attached :cover
    has_many :critics, as: :criticable, dependent: :destroy
    has_many :involved_companies, dependent: :destroy
    has_many :companies, through: :involved_companies
    has_and_belongs_to_many :platforms
    has_and_belongs_to_many :genres
    has_many :expansions, class_name: "Game", 
                                            foreign_key: "parent_id", 
                                            dependent: :destroy, 
                                            inverse_of: "parent"
    belongs_to :parent, class_name: "Game", optional: true
    
    validates :name, presence: true
    validates :summary, presence: true, length: {in: 10..250}
    validates :category, presence: true
    validates :cover, presence: false 

    enum category: { main_game: 0, expansion: 1}

    has_one_attached :cover
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game, only: %i[ show edit update destroy add_genre add_platform add_developer add_publisher remove_genre remove_platform remove_developer remove_publisher]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
    # @genres = Genre.all
    # @platforms = Platform.all
  end
 
  # PATCH /games/:id/add-genre
  def add_genre
    genre = Genre.find(params[:genre_id])
    @game.genres << genre
    redirect_to @game
  end

  def add_platform
    platform = Platform.find(params[:platform_id])
    @game.platforms << platform
    redirect_to @game
  end

  def add_developer
    company = Company.find(params[:company_id])
    @game.involved_companies.create(developer: true, publisher: false, company: company)
    redirect_to @game
  end

  def add_publisher
    company = Company.find(params[:company_id])
    @game.involved_companies.create(developer: false, publisher: true, company: company)
    redirect_to @game
  end

  def remove_genre
    genre = Genre.find(params[:genre_id])
    @game.genres.delete(genre)
    redirect_to games_path
  end

  def remove_platform
    platform = Platform.find(params[:platform_id])
    @game.platforms.delete(platform)
    redirect_to games_path
  end

  def remove_developer
    company = InvolvedCompany.find(params[:company_id])
    @game.involved_companies.delete(company)
    redirect_to games_path
  end

  def remove_publisher
    company = InvolvedCompany.find(params[:company_id])
    @game.involved_companies.delete(company)
    redirect_to games_path
  end


  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game, notice: "Game was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: "Game was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end


  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: "Game was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :summary, :release_date, :category, :rating, :cover)
    end

    def genre_params
      params.require(:genre).permit(:id, :name)
    end

    def  platform_params
      params.require(:platform).permit(:id, :name)
    end

    def involved_companies_params
      params.require(:involved_company).permit(:id, :name)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field flex-form">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "border_8px"%>
  </div>

  <div class="field flex-form">
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_area :summary, class: "border_8px" %>
  </div>

  <div class="field flex-form">
    <%= form.label :release_date, style: "display: block" %>
    <%= form.date_field :release_date, class: "border_8px" %>
  </div>

  <div class="field flex-form">
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category, Game.categories.keys.map{ |key| [key.humanize, key] }, selected: game.category || :draft %>
  </div>

  <div class="field flex-form">
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating, class: "border_8px" %>
  </div>
  
  <div class="flex-form margin_block_start">
    <%= form.label :cover, style: "display: block" %>
    <%= image_tag @game.cover, alt: "Image logo", class: "image" %>
    <%= form.file_field :cover, class: "border_8px margin_block_start" %>
  </div>

  <div class="flex-form margin_block_start">
    <%= form.submit class: "button button--primary"%>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>", class="margin_block_start">
  <% if game.cover.attached? %>
    <div>
      <%= image_tag game.cover, alt: "Image logo" %>
    </div>
  <% end %>

  <p>
    <strong>Name:</strong>
    <%= game.name %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= game.release_date %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= game.summary %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= game.rating %>
  </p>

  <p>Critics: <%= game.critics.size %></p>

</div>

app/views/games/edit.html.erb
<section class = "section-md flex">
  <div class = "container-md background_white">
    <h1 class="center margin_block_start">Editing game</h1>

    <%= render "form", game: @game %>

    <br>

    <div>
      <%= link_to "Show this game", @game, class: "text-decoration-none" %> |
      <%= link_to "Back to games", games_path, class: "text-decoration-none" %>
    </div>
  </div>
</section>

app/views/games/index.html.erb
<section class="section-sm">
  <div class="container-sm">
    <p style="color: green"><%= notice %></p>
    <h1 class="head-sm mb-1">Games</h1>

    <button class="button button--primary button-sm mb-1">
      <%= link_to "New game", new_game_path, class: "game-create-button"%>
    </button>

    <div>
      <% @games.each do |game| %>
        <div class="game--card">
          <div class="game__card--image">
            <%= link_to game_path(game) do%>
              <% if game.cover.attached? %>
                <%= image_tag game.cover %>
              <% else %>
                <%= image_tag "games/default_game_image.jpg"%>
              <% end %>
            <% end %>
          </div>
          <div class="game__card--description">
            <div class="game__card--description__header">
              <h2><%= game.name %></h2>
              <p><%= game.release_date.year %></p>
            </div>
            <div class="game__card--description__body">
              <p><%= game.summary %></p>
            </div>
            <div class="game__card--description__footer">
              <p><%= game.critics.length %> critics</p>
              <div class="game__card--description__footer--buttons">
                <%= link_to  edit_game_path(game) do %>
                  <% image_tag "icons/edit.png" %>
                <% end %>
                <%= link_to game_path(game), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                  <% image_tag "icons/erased.png"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<section class = "section-md">
  <div class = "container-md">
    <div class="gray-100 padding-16px">
      <p style="color: green"><%= notice %></p>

      <div class="image_container">
        <%= image_tag @game.cover, alt: "Image logo", class: "image" %>
      </div>

      <div class="game_id_header margin_block_start">
        <div class="game_name_year">
          <div class="game-name">
            <%= @game.name %>
          </div>

          <div class="year_game">
            <%= @game.release_date.strftime('%Y') %>
          </div>
        </div>

        <div class="button button--secondary">
          <%= @game.rating %>
        </div>
      </div>

      <div class="select_details_critics margin_block_start">
        <div>
          <span class="game_details">Game Details</span>
        </div>
        <div>
          <span class="game_details">Critics (<%=@game.critics.size%>)</span>
        </div>
      </div>

      <div class="margin_block_start">
        <%= @game.summary %>
      </div>

      <div>
        <strong>Genres:</strong>
        <div class="labels_group">
          <% @game.genres.map do |genre| %>
            <div class="label">
              <%= genre.name %> | <%= link_to 'X', remove_genre_game_path(@game, genre_id: genre.id), data: { turbo_method: :delete } %>
            </div>
          <% end %>
        </div>
      </div>

      <div>
        <strong>Platforms:</strong>
        <div class="labels_group">
          <% @game.platforms.map do |platform| %>
            <div class="label">
              <%= platform.name %> | <%= link_to 'X', remove_platform_game_path(@game, platform_id: platform.id), data: { turbo_method: :delete } %>
            </div>
          <% end %>
        </div>
      </div>

      <div>
        <strong>Dev companies</strong>
        <div class="labels_group">
          <% @game.involved_companies.where(developer: true).each do |ic| %>
            <div class="label">
              <%= ic.company.name %> | <%= link_to 'X', remove_developer_game_path(@game, company_id: ic.id), data: { turbo_method: :delete } %>
            </div>
          <% end %>
        </div>
      </div>

      <div>
        <strong>Pub companies</strong>
        <div class="labels_group">
          <% @game.involved_companies.where(publisher: true).each do |ic| %>
          <div class="label">
            <%= ic.company.name %> | <%= link_to 'X', remove_publisher_game_path(@game, company_id: ic.id), data: { turbo_method: :delete } %>
          </div>
          <% end %>
        </div>
      </div>

      <div class="margin_block_start">
        <%= form_with(url: add_genre_game_path(@game)) do |form| %>
          <%#= form.label :genre %>
          <%= form.collection_select :genre_id, (Genre.all - @game.genres), :id, :name, { prompt: true } %>
          <%= form.submit "ADD GENRE" %>
        <% end %>
      </div>

      <div class="margin_block_start">
        <%= form_with(url: add_platform_game_path(@game)) do |form| %>
          <%#= form.label :platform %>
          <%= form.collection_select :platform_id, (Platform.all - @game.platforms), :id, :name, { prompt: true } %>
          <%= form.submit "ADD PLATFORM" %>
        <% end %>
      </div>

      <div class="margin_block_start">
        <%= form_with(url: add_developer_game_path(@game)) do |form| %>
          <%= form.collection_select :company_id, (Company.all), :id, :name, { prompt: true }%>
          <%= form.submit "ADD DEVELOPER"%>
        <% end %>
      </div>

      <div class="margin_block_start">
        <%= form_with(url: add_publisher_game_path(@game)) do |form| %>
          <%= form.collection_select :company_id, (Company.all), :id, :name, { prompt: true }%>
          <%= form.submit "ADD PUBLISHER"%>
        <% end %>
      </div>
      
    </div>


    <%# CRITICS STARTS %>
    <%# CRITICS FINISH  %>

    <div class="gray-100">
      <%= link_to "Edit this game", edit_game_path(@game), class:"text-decoration-none" %>
      <%= link_to "Back to games", games_path, class:"text-decoration-none" %>

      <%= button_to "Destroy this game", @game, method: :delete, class:"text-decoration-none margin_block_start" %>
    </div>
  </div>
</section>