config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :involved_companies
  # resources :users
  resources :genres
  resources :platforms

  
  resources :games do 
    post "add_genre", on: :member
    post "add_platform", on: :member
    post "add_developer", on: :member
    post "add_publisher", on: :member
    delete "remove_genre", on: :member
    delete "remove_platform", on: :member
    delete "remove_developer", on: :member
    delete "remove_publisher", on: :member

    resources :critics, only: %i[create destroy]
  end

  resources :companies do
    resources :critics, only: %i[create destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "games#index"
  # get "/profile", to: "users#show", as: "user"
end

app/models/company.rb
class Company < ApplicationRecord
    has_one_attached :cover
    has_many :involved_companies, dependent: :destroy
    has_many :games, through: :involved_companies
    has_many :critics, as: :criticable, dependent: :nullify

    validates :name, presence: true
    validates :description, presence: true, length: {in: 10..250}
    validates :cover, presence: false 
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
    @critics = @company.critics
    @critic_new = Critic.new
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company, notice: "Company was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to @company, notice: "Company was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to companies_url, notice: "Company was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :description, :start_date, :country, :cover)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div>
  <div class="company--banner-img">
    <% if company.cover.attached? %>
        <%= image_tag company.cover %>
    <% else %>
        <%= image_tag "companies/default_company_image.png" %>
    <% end %>
  </div>

  <h2 class="head-sm"><%= company.name%></h2>
  <p class="text-xs mb-1.5"><%= company.start_date %> - <%= company.country%></p>

  <input type="radio" id="c_critics" name="selection" checked>
  <input type="radio" id="c_games" name="selection" >
  
  <div class="tabs">
    <div class="tabs-element-games">
      <label for="c_critics" id="toggle_games">
          <h3 class="text-md mb-1.5">Company Details</h3>
      </label>
    </div>
    <div class="tabs-element-critics">
      <label for="c_games" id="toggle_critics">
        <h2 class="text-md mb-1.5">Critics (<%= critics.length %>)</h2>
      </label>
    </div>
  </div>

    <!--Details-->
  <div class="expandable-games"> 
    <div class="mb-1.5">
      <p class="text-xs"> <%= company.description %> </p>
    </div>
    <%= render "games", company: company%>
  </div>


  <!--Critics-->
  <div class="expandable-critics">
    <%= render "critics", company: company, critics: critics, critic_new: critic_new %>
  </div>
  <button class="button--default category--form__button">
    <%= link_to "Back", companies_path, class: "gray-700 text-decoration-none"   %>
  </button>
</div>

app/views/companies/_critics.html.erb
<div>
    <div class="company-critics--create">
        <%= form_with url: company_critics_path(company), model: critic_new do |form| %>
            <div class="mb-0.5">
                <%= form.text_field :title, placeholder: "Critic title", class: "input" %>
                <% critic_new.errors.full_messages_for(:title).each do |message| %>
                    <div><%= message %></div>
                <% end %>
            </div>
            <div>
                <%= form.text_area :body, placeholder: "Critic body...", class: "input"%>
                <% critic_new.errors.full_messages_for(:body).each do |message| %>
                    <div><%= message %></div>
                <% end %>
            </div>
            <div>
                <%= form.submit class: "button button--primary btn-width100 overline"%>
            </div>
        <% end %>
    </div>
    <% critics.each do |critic| %>
        <div class="company-critics">
            <div class="company-critics__header"> <!--Critic header-->
                <h3><%= critic.title %></h3>
                <p>By <%= critic.user.username %></p>
            </div>
            <div class="company-critics__body">  <!--Critic body-->
                <p><%= critic.body %></p>
            </div>
            <div class="company-critics__footer">   <!-- Critic footer -->
                <p> Send <%= time_ago_in_words(critic.created_at) %> ago</p>
                <%#= link_to "Delete critic",  company_critic_path(company, critic),  method: "delete" %>
                <%= link_to company_critic_path(company, critic), data: { turbo_method: :delete } do %>
                    <%= image_tag "icons/erased.png"%>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-1">
    <%= form.label :name, style: "display: block", class: "company-form__label mb-0.25" %>
    <%= form.text_field :name, class: "input", placeholder: "Company SA"%>
  </div>

  <div class="mb-1">
    <%= form.label :description, style: "display: block", class: "company-form__label mb-0.25" %>
    <%= form.text_area :description, class: "input", placeholder: "About the company..." %>
  </div>

  <div class="mb-1">
    <%= form.label :start_date, style: "display: block", class: "company-form__label mb-0.25" %>
    <%= form.date_field :start_date, class: "input"%>
  </div>

  <div class="mb-1">
    <%= form.label :country, style: "display: block", class: "company-form__label mb-0.25" %>
    <%= form.text_field :country, class: "input" , placeholder: "Somewhere"%>
  </div>

  <div class="mb-1">
    <%= form.label :cover, style: "display: block", class: "company-form__label mb-0.25" %>
    <%= form.file_field :cover, accept: "image/png, image/jpg"%>
  </div>  

  <div class="mb-1">
    <%= form.submit class:"button button--primary btn-width100 overline" %>
  </div>
<% end %>

app/views/companies/_games.html.erb
<div>
    <h2 class="company-games--header mb-1">Games(<%= company.games.length %>)</h2>
    <% company.games.map do |game| %>
        <div class="company-games__card">
            <div class="company-games__card--image"> <!--Image-->
                <%= link_to game_path(game) do%>
                    <% if game.cover.attached? %>
                        <%= image_tag game.cover%>
                    <% else %>
                        <%= image_tag "games/default_game_image.jpg"%>
                    <% end %>
                <% end %>
            </div>
            <div class="company-games__card--decription"> <!-- Description -->
                <div class="company-games__card--decription__header">
                    <div class="company-games__card--decription__header--title">
                        <h3> <%= game.name %> </h3>
                        <p>  <%=  game.release_date.year %> </p>
                    </div>
                    <div class="company-games__card--decription__header--rating">
                        <h3> <%= game.rating %> </h3>
                    </div>
                </div>
                <div class="company-games__card--decription__body">
                    <p><%= game.summary %></p>
                </div>
                <div class="company-games__card--decription__footer">
                    <p><%= game.critics.length %> critics </p>
                    <div class="company-games__card--decription__footer---buttons">
                        <%= link_to do %>
                            <%= image_tag "icons/edit.png"%>
                        <% end %>
                        <%= link_to do %>
                            <%= image_tag "icons/erased.png"%>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/companies/edit.html.erb
<section class="section-sm">
  <div class="container-sm">
    <h1 class="head-sm mb-1">Editing company</h1>
    <%= render "form", company: @company %>
    <div>
      <%#= link_to "Show this company", @company %> 
      <button class="button button--default btn-width100 overline">
        <%= link_to "Back to companies", companies_path, class: "gray-700 text-decoration-none" %>
      </button>
    </div>
  </div>
</section>

app/views/companies/index.html.erb
<section class="section-sm">
  <div class= "container-sm company">
    <p style="color: green"><%= notice %></p>
    <h1 class= "head-sm mb-1 ">Companies</h1>

    <button class="button button--primary button--sm mb-1">
      <%= link_to "New company", new_company_path, class: "company-create-button" %>
    </button>

    <div>
      <% @companies.each do |company| %>
        <div class="company--card">
          <div class="company__card--image"> <!-- Company cover image -->
            <%= link_to company_path(company) do%>
              <% if company.cover.attached? %>
                <%= image_tag company.cover %>
              <% else %>
                <%= image_tag "companies/default_company_image.png" %>
              <% end %>
            <% end %>
          </div>
          <div class="company__card--description"> <!-- Company description -->
            <div class="company__card--description__header"> <!-- Header -->
              <h2><%= company.name %></h2>
              <p><%= company.created_at.year %> - <%= company.country%></p>
            </div>
            <div class="company__card--description__body">
              <p><%= company.description %></p>
            </div>
            <div class="company__card--description__footer"> <!-- Footer -->
              <p><%= company.games.length %> games<p>
              <div class= "company__card--description__footer--buttons ">
                <%= link_to edit_company_path(company) do %>
                  <% image_tag "icons/edit.png"%>
                <% end %>
                <%= link_to company_path(company), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                  <% image_tag "icons/erased.png"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>  

app/views/companies/new.html.erb
<section class="section-sm">
  <div class="container-sm">
    <h1 class="head-sm mb-1">New company</h1>
    <%= render "form", company: @company %>
    <div>
      <button class="button button--default btn-width100 overline">
        <%= link_to "Back", companies_path, class: "gray-700 text-decoration-none" %>
      </button>
    </div>
  </div>
</section>

app/views/companies/show.html.erb
<section class="section-sm">
  <div class="container-sm company">
    <p style="color: green"><%= notice %></p>
    <%= render "company", company: @company, critics: @critics, critic_new: @critic_new %>
  </div>
</section>

<!--
<div>
  <%# = link_to "Edit this company", edit_company_path(@company) %> |
  <%# = link_to "Back to companies", companies_path %>

  <%# = button_to "Destroy this company", @company, method: :delete %>
</div>
-->